# ===========================================
# DEMO DATABASE
# ===========================================

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kv-infosys
type: Opaque
data:
  username: a3ZpbmZvc3lzX3VzZXI=
  password: c2VjdXJlX3Bhc3N3b3JkXzEyMyE=
  database: a3ZpbmZvc3lzX2Ri
  #TODO: password from secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kv-infosys
data:
  POSTGRES_DB: kvinfosys_db
  POSTGRES_USER: kvinfosys_user
  PGDATA: /var/lib/postgresql/data/pgdata

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: kv-infosys
  labels:
    app: postgres
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: database
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: PGDATA
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: PGDATA
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kv-infosys
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  type: ClusterIP

---

