# ===========================================
# DEMO DATABASE
# ===========================================

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kv-infosys
type: Opaque
data:
  username: a3ZpbmZvc3lzX3VzZXI=
  password: c2VjdXJlX3Bhc3N3b3JkXzEyMyE=
  database: a3ZpbmZvc3lzX2Ri
  #TODO: password from secret
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: kv-infosys
data:
  POSTGRES_DB: kvinfosys_db
  POSTGRES_USER: kvinfosys_user
  PGDATA: /var/lib/postgresql/data/pgdata

---

