# ===========================================
# NETWORK POLICIES
# ===========================================

#TODO: Implement following Network Policies
# Default Deny Rule (Allow Egress DNS, http)
# Allow frontend to backend communication
# Allow backend to database communication
# Allow ingress controller to frontend

